# Generated by Django 5.1.3 on 2024-11-06 08:27

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Фотография')),
                ('social_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Участник организации',
                'verbose_name_plural': 'Участники организации',
            },
        ),
    ]
