# Generated by Django 5.1.3 on 2024-11-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Введите имя клиента, оставившего отзыв.', max_length=100, verbose_name='Имя клиента')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Выберите оценку от 1 до 5.', verbose_name='Оценка')),
                ('review_text', models.TextField(help_text='Введите текст отзыва.', verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время публикации отзыва. Устанавливается автоматически при создании записи.', verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован ли отзыв на сайте.', verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
